# Generated by Django 4.2 on 2024-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://cdn-icons-png.flaticon.com/512/1377/1377194.png",
                max_length=500,
            ),
        ),
    ]
