# Generated by Django 4.2.6 on 2024-09-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="genre",
            field=models.CharField(default="action", max_length=100),
        ),
    ]
